### ISSUE TITLE
Awkward space after flag

### ISSUE THREAD

**Issue by Tofandel** [yogakurniawan/vue-tel-input-vuetify#11]
![image](https://user-images.githubusercontent.com/6115458/86337325-3bcec180-bc51-11ea-8bba-ed149793445d.png)

Current workaround
```css
.vue-tel-input-vuetify .country-code {
   width: 70px;
   padding-right: 10px;
}
```
